config/routes.rb
Rails.application.routes.draw do
  root to: 'places#index'
  resources :places, only: %w(show create)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord
  require 'csv'

  geocoded_by :address

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      place = Place.create!(row.to_hash)
      GeocodeWorker.perform_async(place.id)
    end
  end

  def address
    [street, city, state, country, zip].compact.join(', ')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
    @places = Place.all
  end

  def show
    @place = Place.find(params[:id])
  end

  def create
    Place.import(params[:file])
    redirect_to :root
  rescue
    redirect_to :root, alert: 'Invalid CSV file format.'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def google_map(place, static = false)
    key = ENV.fetch('GOOGLE_MAPS_KEY')
    coordinates = "#{place.latitude}, #{place.longitude}"
    static ? map_image(key, coordinates) : map_iframe(key, coordinates)
  end

  def map_image(key, coordinates)
    src = "https://maps.googleapis.com/maps/api/staticmap?key=#{key}&center=#{coordinates}&size=300x100&zoom=17&markers=color:blue%7C#{coordinates}"
    image_tag(src)
  end

  def map_iframe(key, coordinates)
    src = "https://www.google.com/maps/embed/v1/place?key=#{key}&q=#{coordinates}"
    content_tag(:iframe, '', src: src, width: '100%', height: 500, frameborder: 0)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlacesTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notifications/_alert.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <div class="alert alert-danger">
      <a href="#" data-dismiss="alert" class="close">×</a>
      <ul>
        <li><%= alert.html_safe %></li>
      </ul>
    </div>
  </div>
</div>

app/views/places/_place.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">
      <span class="glyphicon glyphicon-map-marker"></span>
      <%= place.address %>
    </h3>
  </div>
  <div class="panel-body">
    <%= link_to 'Place details', place_path(place) %>
    <div class="static-map-container">
      <%= google_map(place, true) if place.geocoded? %>
    </div>
  </div>
</div>

app/views/places/_place_form.html.erb
<div class="place-form">
  <%= form_tag places_path, multipart: true do %>
    <%= file_field_tag :file, class: 'hidden jsFileField' %>
    <%= button_tag 'Download from CSV', class: 'btn btn-primary center-block jsDownloadBtn' %>
  <% end %>
</div>

app/views/places/index.html.erb
<div class="container">
  <%= render('notifications/alert', alert: alert) if alert.present? %>

  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <%= render 'place_form' %>
    </div>
  </div>

  <% if @places.any? %>
    <div class="row">
      <div class="col-sm-8 col-sm-offset-2">
        <% @places.each do |place| %>
          <%= render 'place', place: place %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/places/show.html.erb
<div class="container show-page-container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <div class="panel panel-primary ">
        <div class="panel-heading">
          <h3 class="panel-title">
            <span class="glyphicon glyphicon-map-marker"></span>
            <%= @place.address %>
          </h3>
        </div>
        <div class="panel-body">
          <%= google_map(@place) %>
        </div>
      </div>
    </div>
  </div>
</div>